### ISSUE TITLE
SDP parser fails to handle additional new line characters

### ISSUE THREAD

**Issue by andrewbonney** [bbc/nmos-device-connection-management-ri#4]
Whilst SDP files typically have a single `\r\n` between each statement, some implementations may include multiple in order to make the files more legible. At present it seems sdpParser.py cannot handle these cases. It should probably be made more permissive in this case.

**Comment by simonrankine** [comment]
Fixed in #5, note re-naming of sdp manager class to sdpManager.py to facilitate refactoring.

**Comment by simonrankine** [comment]
Fixed in #5, note re-naming of sdp manager class to sdpManager.py to facilitate refactoring.
